### ISSUE TITLE
feat: update the organization readme

### ISSUE THREAD

**Issue by levivannoort** [amplication/.github#5]
This includes making the look more aligned with our `amplication/amplication` readme - also fixing and cleaning up the links.

**Comment by levivannoort** [comment]
Previous state [N/A]
![image](https://github.com/amplication/.github/assets/73097785/6ebaf48f-fffc-4f89-9eaa-65961297f1d8)

---

Current state [04/10/2023]:
![image](https://github.com/amplication/.github/assets/73097785/4d4c6fc9-5350-4da5-81e3-842656c00796)

**Comment by overbit** [comment]
@levivannoort how can we review this?

**Comment by levivannoort** [comment]
> @levivannoort how can we review this?

@overbit Attached the PR, which wasn't attached previously. I guess in a 'how can we review this?' would be more along the lines of does it make sense from a design point of view & is all the needed information in there.

**Comment by overbit** [comment]
Let's check with @GreenMachine01, @mulygottlieb and @yuval-hazaz if they have any feedback / concern

**Comment by mulygottlieb** [comment]
@levivannoort, it lgtm. I did add a couple of small comments on your PR./
@GreenMachine01  - do you have any other comments?
